# Generated by Django 2.2.4 on 2019-08-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Log_Type',
            fields=[
                ('no', models.IntegerField(db_column='lno', primary_key=True, serialize=False, verbose_name='链接编号')),
                ('device', models.IntegerField(db_column='device', verbose_name='设备编号')),
                ('types', models.IntegerField(db_column='types', verbose_name='类型编号')),
            ],
            options={
                'db_table': 'tb_device_log_type_link',
            },
        ),
        migrations.CreateModel(
            name='Device_sheet',
            fields=[
                ('no', models.IntegerField(db_column='dno', primary_key=True, serialize=False, verbose_name='设备编号')),
                ('name', models.CharField(db_column='dname', max_length=20, verbose_name='设备名称')),
                ('describtion', models.CharField(db_column='ddes', max_length=10, verbose_name='设备描述')),
            ],
            options={
                'db_table': 'tb_dev',
            },
        ),
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('tdno', models.IntegerField(db_column='dtno', primary_key=True, serialize=False, verbose_name='设备编号')),
                ('name', models.CharField(db_column='dtname', max_length=20, verbose_name='设备名称')),
            ],
            options={
                'db_table': 'tb_devtype',
            },
        ),
        migrations.CreateModel(
            name='Log_type',
            fields=[
                ('no', models.IntegerField(db_column='ltno', primary_key=True, serialize=False, verbose_name='提醒编号')),
                ('name', models.CharField(db_column='ltname', max_length=20, verbose_name='提醒类型')),
            ],
            options={
                'db_table': 'tb_logtype',
            },
        ),
        migrations.CreateModel(
            name='Log_sheet',
            fields=[
                ('no', models.IntegerField(db_column='lno', primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(db_column='lname', max_length=20, verbose_name='记录名称')),
                ('logdate', models.DateTimeField(db_column='ldate', verbose_name='记录日期')),
                ('reminddate', models.DateTimeField(db_column='rdate', verbose_name='提醒日期')),
                ('dept', models.ForeignKey(db_column='dno', on_delete=django.db.models.deletion.PROTECT, to='devicealert.Device_sheet', verbose_name='记录设备编号')),
            ],
            options={
                'db_table': 'tb_log',
            },
        ),
        migrations.AddField(
            model_name='device_sheet',
            name='dtype',
            field=models.ForeignKey(db_column='dtno', null=True, on_delete=django.db.models.deletion.PROTECT, to='devicealert.Device_type', verbose_name='设备类型'),
        ),
    ]
